services:
  postgres:
    image: postgres:16
    container_name: linkbold-db
    restart: always
    environment:
      POSTGRES_USER: shortuser
      POSTGRES_PASSWORD: shortpass
      POSTGRES_DB: shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortuser -d shortener"]
      interval: 5s
      retries: 10
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: linkbold-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgres://shortuser:shortpass@postgres:5432/shortener
      BASE_URL: http://linkbold:5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    command: npm start


volumes:
  pgdata:
